insert into public.courses (name, city, region, country) values
  ('Westwood Country Club', 'Vienna', 'VA', 'USA'),
  ('Penderbrook Golf Club', 'Fairfax', 'VA', 'USA'),
  ('Jefferson District Golf Course', 'Falls Church', 'VA', 'USA'),
  ('Burke Lake Golf Center', 'Fairfax Station', 'VA', 'USA'),
  ('Twin Lakes Golf Course', 'Clifton', 'VA', 'USA'),
  ('East Potomac Golf Links', 'Washington', 'DC', 'USA'),
  ('Langston Golf Course', 'Washington', 'DC', 'USA'),
  ('Rock Creek Park Golf', 'Washington', 'DC', 'USA'),
  ('Northwest Golf Course', 'Silver Spring', 'MD', 'USA'),
  ('Blue Mash Golf Course', 'Laytonsville', 'MD', 'USA'),
  ('Real Club Sevilla Golf', 'Alcalá de Guadaíra', 'Sevilla', 'Spain'),
  ('Real Club Pineda de Sevilla', 'Sevilla', 'Sevilla', 'Spain'),
  ('Chaparral Golf Club', 'Mijas', 'Málaga', 'Spain'),
  ('Golf Torrequebrada', 'Benalmádena', 'Málaga', 'Spain'),
  ('Lauro Golf Resort', 'Alhaurín de la Torre', 'Málaga', 'Spain'),
  ('La Cala Golf', 'La Cala de Mijas', 'Málaga', 'Spain'),
  ('Real Guadalhorce Club de Golf', 'Málaga', 'Málaga', 'Spain'),
  ('Myrtle Beach National', 'Myrtle Beach', 'SC', 'USA'),
  ('Dunes Golf and Beach Club', 'Myrtle Beach', 'SC', 'USA'),
  ('TPC Myrtle Beach', 'Murrells Inlet', 'SC', 'USA'),
  ('Myrtlewood Golf Club', 'Myrtle Beach', 'SC', 'USA'),
  ('Arrowhead Country Club', 'Myrtle Beach', 'SC', 'USA'),
  ('Arcadian Shores Golf Club', 'Myrtle Beach', 'SC', 'USA'),
  ('TPC Scottsdale', 'Scottsdale', 'AZ', 'USA'),
  ('Scottsdale Silverado Golf Club', 'Scottsdale', 'AZ', 'USA'),
  ('Gainey Ranch Golf Club', 'Scottsdale', 'AZ', 'USA'),
  ('Troon North Golf Club', 'Scottsdale', 'AZ', 'USA'),
  ('Grayhawk Golf Club', 'Scottsdale', 'AZ', 'USA'),
  ('Talking Stick Golf Club', 'Scottsdale', 'AZ', 'USA'),
  ('Pinehurst Resort', 'Pinehurst', 'NC', 'USA'),
  ('Pinehurst No. 8', 'Pinehurst', 'NC', 'USA'),
  ('Southern Pines Golf Club', 'Southern Pines', 'NC', 'USA'),
  ('Forest Creek Golf Club', 'Pinehurst', 'NC', 'USA'),
  ('Legacy Golf Club', 'Aberdeen', 'NC', 'USA'),
  ('Robert Trent Jones Oceanfront Golf Course', 'Hilton Head Island', 'SC', 'USA'),
  ('Harbour Town Golf Links', 'Hilton Head Island', 'SC', 'USA'),
  ('Hilton Head National Golf Course', 'Bluffton', 'SC', 'USA'),
  ('Heron Point by Pete Dye', 'Hilton Head Island', 'SC', 'USA'),
  ('Atlantic Dunes by Davis Love III', 'Hilton Head Island', 'SC', 'USA'),
  ('Shingle Creek Golf Club', 'Orlando', 'FL', 'USA'),
  ('Dubsdread Golf Course', 'Orlando', 'FL', 'USA'),
  ('The Ritz-Carlton Golf Club, Grande Lakes', 'Orlando', 'FL', 'USA'),
  ('Waldorf Astoria Golf Club', 'Orlando', 'FL', 'USA'),
  ('ChampionsGate Golf Club', 'Championsgate', 'FL', 'USA'),
  ('Lake Placid Club', 'Lake Placid', 'NY', 'USA'),
  ('Craig Wood Golf & Country Club', 'Lake Placid', 'NY', 'USA'),
  ('Saranac Lake Golf Club', 'Lake Placid', 'NY', 'USA'),
  ('Whiteface Club & Resort', 'Lake Placid', 'NY', 'USA'),
  ('Pebble Beach Golf Links', 'Pebble Beach', 'CA', 'USA'),
  ('Cypress Point Club', 'Pebble Beach', 'CA', 'USA'),
  ('Poppy Hills Golf Course', 'Pebble Beach', 'CA', 'USA'),
  ('Pacific Grove Golf Links', 'Pacific Grove', 'CA', 'USA'),
  ('Bandon Dunes Golf Resort', 'Bandon', 'OR', 'USA'),
  ('Pacific Dunes', 'Bandon', 'OR', 'USA'),
  ('Bandon Trails', 'Bandon', 'OR', 'USA'),
  ('Sheep Ranch', 'Bandon', 'OR', 'USA'),
  ('Old Macdonald', 'Bandon', 'OR', 'USA'),
  ('Mauna Lani Golf', 'Waimea', 'HI', 'USA'),
  ('Nanea Golf Club', 'Kailua-Kona', 'HI', 'USA'),
  ('Royal Hawaiian Golf Club', 'Kailua', 'HI', 'USA'),
  ('Wailea Emerald Golf Course', 'Kihei', 'HI', 'USA'),
  ('Poipu Bay Golf Course', 'Koloa', 'HI', 'USA'),
  ('Augusta National Golf Club', 'Augusta', 'GA', 'USA'),
  ('Champions Retreat Golf Club', 'Evans', 'GA', 'USA'),
  ('Forest Hills Golf Course', 'Augusta', 'GA', 'USA'),
  ('Bartram Trail Golf Club', 'Evans', 'GA', 'USA'),
  ('Augusta Country Club', 'Augusta', 'GA', 'USA'),
  ('The Quarry Golf Course', 'San Antonio', 'TX', 'USA'),
  ('Spanish Oaks Golf Club', 'Austin', 'TX', 'USA'),
  ('Escondido Golf & Lake Club', 'Horseshoe Bay', 'TX', 'USA'),
  ('Canyon Springs Golf Club', 'San Antonio', 'TX', 'USA'),
  ('Whispering Pines Golf Club', 'Trinity', 'TX', 'USA'),
  ('Arcadia Bluffs Golf Club', 'Arcadia', 'MI', 'USA'),
  ('Forest Dunes Golf Club', 'Roscommon', 'MI', 'USA'),
  ('American Dunes Golf Club', 'Grand Haven', 'MI', 'USA'),
  ('Bay Harbor Golf Club', 'Bay Harbor', 'MI', 'USA'),
  ('Pilgrim''s Run Golf Club', 'Pierson', 'MI', 'USA'),
  ('Whistling Straits', 'Sheboygan', 'WI', 'USA'),
  ('Blackwolf Run - River Course', 'Kohler', 'WI', 'USA'),
  ('Blackwolf Run - Meadow Valleys', 'Kohler', 'WI', 'USA'),
  ('The Bull at Pinehurst Farms', 'Sheboygan Falls', 'WI', 'USA'),
  ('Shadow Creek Golf Course', 'North Las Vegas', 'NV', 'USA'),
  ('Southern Highlands Golf Club', 'Las Vegas', 'NV', 'USA'),
  ('TPC Las Vegas', 'Las Vegas', 'NV', 'USA'),
  ('Reflection Bay Golf Club', 'Henderson', 'NV', 'USA'),
  ('Las Vegas Paiute Golf Resort', 'Las Vegas', 'NV', 'USA'),
  ('The Broadmoor Golf Club', 'Colorado Springs', 'CO', 'USA'),
  ('Castle Pines Golf Club', 'Castle Rock', 'CO', 'USA'),
  ('Arrowhead Golf Club', 'Littleton', 'CO', 'USA'),
  ('Colorado Golf Club', 'Parker', 'CO', 'USA'),
  ('Sanctuary Golf Course', 'Sedalia', 'CO', 'USA'),
  ('The Golf Club of Tennessee', 'Kingston Springs', 'TN', 'USA'),
  ('Troubadour Golf & Field Club', 'College Grove', 'TN', 'USA'),
  ('Sweetens Cove Golf Club', 'South Pittsburg', 'TN', 'USA'),
  ('Spring Creek Ranch', 'Collierville', 'TN', 'USA'),
  ('Gaylord Springs Golf Links', 'Nashville', 'TN', 'USA'),
  ('St Andrews Links (Old Course)', 'St Andrews', 'Fife', 'Scotland'),
  ('Carnoustie Golf Links', 'Carnoustie', 'Angus', 'Scotland'),
  ('Royal Troon', 'Troon', 'Ayrshire', 'Scotland'),
  ('Muirfield', 'Gullane', 'East Lothian', 'Scotland'),
  ('Gleneagles', 'Auchterarder', 'Perthshire', 'Scotland'),
  ('Turnberry (Ailsa Course)', 'Turnberry', 'Ayrshire', 'Scotland'),
  ('Royal County Down', 'Newcastle', 'County Down', 'Northern Ireland'),
  ('Royal Portrush Golf Club', 'Portrush', 'County Antrim', 'Northern Ireland'),
  ('Ballybunion Golf Club', 'Ballybunion', 'County Kerry', 'Ireland'),
  ('Lahinch Golf Club', 'Lahinch', 'County Clare', 'Ireland'),
  ('Royal Birkdale', 'Southport', 'Merseyside', 'England'),
  ('Royal St George''s', 'Sandwich', 'Kent', 'England'),
  ('RTJ Golf Trail at Ross Bridge', 'Hoover', 'AL', 'USA'),
  ('RTJ Golf Trail at Grand National', 'Opelika', 'AL', 'USA'),
  ('RTJ Golf Trail at Capitol Hill', 'Prattville', 'AL', 'USA'),
  ('RTJ Golf Trail at Cambrian Ridge', 'Greenville', 'AL', 'USA'),
  ('RTJ Golf Trail at Oxmoor Valley', 'Birmingham', 'AL', 'USA'),
  ('RTJ Golf Trail at The Shoals', 'Muscle Shoals', 'AL', 'USA'),
  ('Firestone Country Club', 'Akron', 'OH', 'USA'),
  ('Sand Ridge Golf Club', 'Chardon', 'OH', 'USA'),
  ('Ohio State University Golf Club (Scarlet Course)', 'Columbus', 'OH', 'USA'),
  ('TPC River''s Bend', 'Maineville', 'OH', 'USA'),
  ('Stone Ridge Golf Club', 'Bowling Green', 'OH', 'USA'),
  ('Oakmont Country Club', 'Oakmont', 'PA', 'USA'),
  ('Stonewall', 'Elverson', 'PA', 'USA'),
  ('Olde Stonewall Golf Club', 'Ellwood City', 'PA', 'USA'),
  ('Moselem Springs Golf Club', 'Fleetwood', 'PA', 'USA'),
  ('Fox Chapel Golf Club', 'Pittsburgh', 'PA', 'USA'),
  ('Windsong Farm Golf Club', 'Maple Plain', 'MN', 'USA'),
  ('Hazeltine National Golf Club', 'Chaska', 'MN', 'USA'),
  ('The Quarry at Giants Ridge', 'Aurora', 'MN', 'USA'),
  ('The Wilderness at Fortune Bay', 'Tower', 'MN', 'USA'),
  ('Dacotah Ridge Golf Club', 'Morton', 'MN', 'USA'),
  ('Olympic Hills Golf Club', 'Eden Prairie', 'MN', 'USA'),
  ('Glenwild Golf Club and Spa', 'Park City', 'UT', 'USA'),
  ('Entrada at Snow Canyon Country Club', 'St. George', 'UT', 'USA'),
  ('Sky Mountain Golf Course', 'Hurricane', 'UT', 'USA'),
  ('Eaglewood Golf Course', 'North Salt Lake', 'UT', 'USA'),
  ('Hidden Valley Country Club', 'Sandy', 'UT', 'USA'),
  ('Baltusrol Golf Club', 'Springfield', 'NJ', 'USA'),
  ('Liberty National Golf Club', 'Jersey City', 'NJ', 'USA'),
  ('Galloway National Golf Club', 'Galloway', 'NJ', 'USA'),
  ('Hollywood Golf Club', 'Deal', 'NJ', 'USA'),
  ('Bayonne Golf Club', 'Bayonne', 'NJ', 'USA'),
  ('Hidden Creek Golf Club', 'Egg Harbor Township', 'NJ', 'USA'),
  ('Chambers Bay Golf Course', 'University Place', 'WA', 'USA'),
  ('Gamble Sands', 'Brewster', 'WA', 'USA'),
  ('Salish Cliffs Golf Club', 'Shelton', 'WA', 'USA'),
  ('Gold Mountain Golf Club', 'Bremerton', 'WA', 'USA'),
  ('The Club at Snoqualmie Ridge', 'Snoqualmie', 'WA', 'USA'),
  ('Palouse Ridge Golf Club', 'Pullman', 'WA', 'USA'),
  ('Tiburón Golf Club', 'Naples', 'FL', 'USA'),
  ('The Quarry Golf Club Naples', 'Naples', 'FL', 'USA'),
  ('LaPlaya Golf Club', 'Naples', 'FL', 'USA'),
  ('TPC Treviso Bay', 'Naples', 'FL', 'USA'),
  ('Royal Poinciana Golf Club', 'Naples', 'FL', 'USA'),
  ('The National Golf Club of Kansas City', 'Parkville', 'MO', 'USA'),
  ('Shoal Creek Golf Course', 'Kansas City', 'MO', 'USA'),
  ('Swope Memorial Golf Course', 'Kansas City', 'MO', 'USA'),
  ('Stone Canyon Golf Club', 'Blue Springs', 'MO', 'USA'),
  ('Drumm Farm Golf Club', 'Independence', 'MO', 'USA'),
  ('Queenstown Harbor Golf', 'Queenstown', 'MD', 'USA'),
  ('Links at Perry Cabin', 'St Michaels', 'MD', 'USA'),
  ('Whiskey Creek Golf Club', 'Ijamsville', 'MD', 'USA'),
  ('Great Hope Golf Course', 'Westover', 'MD', 'USA'),
  ('Blue Heron Golf Course', 'Stevensville', 'MD', 'USA'),
  ('Quivira Golf Club', 'Cabo San Lucas', 'BCS', 'Mexico'),
  ('Cabo del Sol', 'Cabo San Lucas', 'BCS', 'Mexico'),
  ('Solmar Golf Links', 'Cabo San Lucas', 'BCS', 'Mexico'),
  ('El Cardonal at Diamante', 'Cabo San Lucas', 'BCS', 'Mexico'),
  ('Diamante Dunes Course', 'Cabo San Lucas', 'BCS', 'Mexico'),
  ('El Dorado Golf & Beach Club', 'San José del Cabo', 'BCS', 'Mexico'),
  ('Punta Espada Golf Club', 'Punta Cana', 'La Altagracia', 'Dominican Republic'),
  ('Corales Golf Course', 'Punta Cana', 'La Altagracia', 'Dominican Republic'),
  ('La Cana Golf Club', 'Punta Cana', 'La Altagracia', 'Dominican Republic'),
  ('Cocotal Golf & Country Club', 'Punta Cana', 'La Altagracia', 'Dominican Republic'),
  ('Iberostar Bávaro Golf Club', 'Punta Cana', 'La Altagracia', 'Dominican Republic'),
  ('Monte Rei Golf & Country Club', 'Vila Nova de Cacela', 'Algarve', 'Portugal'),
  ('Quinta do Lago South Course', 'Almancil', 'Algarve', 'Portugal'),
  ('Quinta do Lago North Course', 'Almancil', 'Algarve', 'Portugal'),
  ('San Lorenzo Golf Course', 'Almancil', 'Algarve', 'Portugal'),
  ('Old Course Vilamoura', 'Quarteira', 'Algarve', 'Portugal'),
  ('Quinta da Ria Golf Course', 'Vila Nova de Cacela', 'Algarve', 'Portugal'),
  ('Royal Melbourne Golf Club', 'Black Rock', 'VIC', 'Australia'),
  ('Victoria Golf Club', 'Cheltenham', 'VIC', 'Australia'),
  ('Kingston Heath Golf Club', 'Heatherton', 'VIC', 'Australia'),
  ('Peninsula Kingswood Country Golf Club', 'Frankston', 'VIC', 'Australia'),
  ('Huntingdale Golf Club', 'Oakleigh South', 'VIC', 'Australia'),
  ('Lake of Isles', 'North Stonington', 'CT', 'USA'),
  ('TPC River Highlands', 'Cromwell', 'CT', 'USA'),
  ('Sterling Farms Golf Course', 'Stamford', 'CT', 'USA'),
  ('Bull''s Bridge Golf Club', 'South Kent', 'CT', 'USA'),
  ('Great River Golf Club', 'Milford', 'CT', 'USA'),
  ('Valhalla Golf Club', 'Louisville', 'KY', 'USA'),
  ('Persimmon Ridge Golf Club', 'Louisville', 'KY', 'USA'),
  ('Heritage Hill Golf Club', 'Shepherdsville', 'KY', 'USA'),
  ('University of Louisville Golf Club', 'Simpsonville', 'KY', 'USA'),
  ('The Pete Dye Course at French Lick', 'French Lick', 'IN', 'USA'),
  ('Chariot Run Golf Club', 'Laconia', 'IN', 'USA'),
  ('The Sagamore Club', 'Noblesville', 'IN', 'USA'),
  ('Purgatory Golf Club', 'Noblesville', 'IN', 'USA'),
  ('Sandy Pines Golf Club', 'De Motte', 'IN', 'USA'),
  ('The Coeur d''Alene Resort Golf Course', 'Coeur d''Alene', 'ID', 'USA'),
  ('Circling Raven Golf Club', 'Worley', 'ID', 'USA'),
  ('CDA National Reserve', 'Coeur d''Alene', 'ID', 'USA'),
  ('Coeur d''Alene Public Golf Club', 'Coeur d''Alene', 'ID', 'USA'),
  ('Santa Ana Golf Club', 'Santa Ana Pueblo', 'NM', 'USA'),
  ('Sandia Golf Club', 'Albuquerque', 'NM', 'USA'),
  ('Paako Ridge Golf Club', 'Sandia Park', 'NM', 'USA'),
  ('Twin Warriors Golf Club', 'Santa Ana Pueblo', 'NM', 'USA'),
  ('The Club at Las Campanas', 'Santa Fe', 'NM', 'USA'),
  ('Royal Isabela', 'Isabela', 'PR', 'Puerto Rico'),
  ('Bahia Beach Resort & Golf Club', 'Río Grande', 'PR', 'Puerto Rico'),
  ('Coco Beach Golf Club', 'Río Grande', 'PR', 'Puerto Rico'),
  ('Grand Reserve Golf Club', 'Río Grande', 'PR', 'Puerto Rico'),
  ('Río Bayamón Golf Course', 'Bayamón', 'PR', 'Puerto Rico'),
  ('Wentworth Club', 'Virginia Water', 'Surrey', 'England');
